### ISSUE TITLE
Update system config management scripts to use robot-specific repositories

### ISSUE THREAD

**Issue by jmount1992** [qcr/system-configs#10]
The issue was originally from [QCR Tools](https://github.com/qcr/tools/issues/18) prior to the separation of QCR Tools and the System Configs Tool.

Ben Talbot's original issue comment:

Goes hand-in-hand with resolving [#12](https://github.com/qcr/tools/issues/12).
[#3](https://github.com/qcr/tools/issues/3) bought these scripts across, but blocked them with stubs at the top until they work with robot-specific repositories.

**Comment by RSLamont** [comment]
Closed with the completion of #11 , #12
