### ISSUE TITLE
Create robot specific system config repositories

### ISSUE THREAD

**Issue by jmount1992** [qcr/system-configs#11]
The issue was originally from [QCR Tools](https://github.com/qcr/tools/issues/12) prior to the separation of QCR Tools and the System Configs Tool.

Ben Talbot Comment:
Old configurations can be found on the develop branch of the deprecated repository: https://github.com/qcr/robot_system_configs/tree/develop

**Comment by RSLamont** [comment]
Duplication of issue #12 see closing comments.
