### ISSUE TITLE
Migrate in utility scripts from `qcr/robot_system_configs`

### ISSUE THREAD

**Issue by jmount1992** [qcr/system-configs#12]
The issue was originally from [QCR Tools](https://github.com/qcr/tools/issues/3) prior to the separation of QCR Tools and the System Configs Tool.

This may have been completed, based on issue comments in QCR Tools.

**Comment by RSLamont** [comment]
Now using qcr-configs organisation for individual robot configs instead of previous system where all robots and scripts were in unified repo (https://github.com/qcr/robot_system_configs).
