### ISSUE TITLE
Template Creation is Cumbersome

### ISSUE THREAD

**Issue by jmount1992** [qcr/system-configs#3]
The issue originally from [QCR Tools](https://github.com/qcr/tools/issues/21) prior to the separation of QCR Tools and the System Configs Tool.

Creating a system config template is currently a little cumbersome. Current process:

```bash
# Track file, but  need to set the hostname to what you want the template to be called
# otherwise when creating template you get an empty repo
system_configs track --hostname <template_name> <file>

# Create template using install (which is semantically confusing)
# Need to set hostname so gets correct files
system_configs install --template <git-relative-url> --hostname <template_name>

# Sync with hostname set to template name
system_configs sync --hostname <template_name>
```

A few potential avenues for improvement:

- Create a template sub-command with its own sub-commands to do anything to do with templates (install, create, etc.):
    - `system_configs template install <arguments>`
    - `system_configs template create <arguments>`
- Create a create template sub-command specifically for dealing with template creating: `system_configs create_template <arguments>`

**Comment by RSLamont** [comment]
Resolved, see updated readme
